Repository openMF/community-app, pull requests merged in 2018-03, with the labels that each got.

#2811 Fix #2808 - Removed "charged payment by" field from edit charges
  app/scripts/controllers/product/EditChargeController.js
Labels: size/XS

#2814 Fix #2813 - Added bread crumb in Fund Mapping
  app/views/search/advsearch.html
Labels: size/XS

#2818 Fix Add button icon
  app/views/centers/viewcenter.html
Labels: size/XS

#2819 Fix delete icon
  app/views/administration/viewuser.html
Labels: size/XS

#2822 Fix #2821 - Fixed hovers
  app/views/system/accountnumberpreferences.html
  app/views/system/entitytoentitymapping.html
  app/views/system/hooks.html
Labels: size/XS

#2829 Fix #2824 Incorrect format of date in Fund Mapping
  app/views/search/advsearch.html
Labels: size/XS

#2830 Fix #2825 Changing Date Format in Settings does not update Date Format of Date Pickers in the app
  app/scripts/modules/datepicker.js
Labels: size/XS

#2831 Fix #2816 - Display Preview
  app/scripts/controllers/product/CreateFixedDepositProductController.js
  app/scripts/controllers/product/CreateLoanProductController.js
  app/scripts/controllers/product/CreateRecurringDepositProductController.js
  app/scripts/controllers/product/CreateSavingProductController.js
  app/scripts/controllers/product/CreateShareProductController.js
  app/views/products/createfixeddepositproduct.html
  app/views/products/createloanproduct.html
  app/views/products/createrecurringdepositproduct.html
  app/views/products/createsavingproduct.html
  app/views/products/createshareproduct.html
Labels: size/XS

#2837 Fix #2836 use uib-tooltip for displaying status
  app/global-translations/locale-en.json
  app/scripts/filters/StatusLookup.js
  app/views/centers/centers.html
  app/views/groups/groups.html
  app/views/organization/employees.html
  app/views/products/charges.html
Labels: size/XS

#2840 Fix #2839 Redundant Breadcrumb Link Removed from Currency Configuration
  app/views/organization/currencyconfig.html
Labels: size/XS

#2844 Fix #2841 Complete Data Showing Up in Share Products, Redundant Next/Previous Buttons Removed
  app/scripts/controllers/product/ShareProductController.js
  app/views/products/shareproducts.html
Labels: size/XS

#2848 Fix #2823 - Add breadcrumbs to AdHocQuery
  app/views/adhocquery/adhocquerylists.html
  app/views/adhocquery/createadhocquery.html
Labels: size/XS

#2849 Fix #2847 - Added missing breadcrumb in attendance
  app/scripts/controllers/centers/CenterAttendanceController.js
  app/scripts/controllers/groups/GroupAttendanceController.js
  app/views/centers/centerattendance.html
  app/views/groups/groupattendance.html
Labels: size/XS

#2815 Fix #2784 - Added form validation to the listed places
  app/views/accounting/add_financial_accounting_mapping.html
  app/views/accounting/createclosure.html
  app/views/accounting/freqposting.html
  app/views/accounting/openingbalances.html
  app/views/accounttransfers/create_standinginstruction.html
  app/views/administration/createuser.html
  app/views/groups/creategroup.html
  app/views/organization/createpaymenttype.html
  app/views/organization/currencyconfig.html
  app/views/organization/smscampaigns/createsmscampaign.html
  app/views/products/createloanproduct.html
  app/views/products/createshareproduct.html
  app/views/system/addaccountnumberpreferences.html
  app/views/system/addhook.html
  app/views/system/createdatatable.html
  app/views/system/edithook.html
Labels: size/S

#2852 Fix #2846 Filter data and Pagination in Reschedule Loan
  app/views/tasks.html
Labels: size/XS

#2856 Fix #2827 - Align the input field
  app/views/organization/createholiday.html
Labels: size/XS

#2860 Fix #2817 - Added num validation
  app/scripts/directives/FormValidateDirective.js
  app/scripts/directives/LateValidateDirective.js
  app/views/products/createcharge.html
  app/views/products/createfixeddepositproduct.html
  app/views/products/createloanproduct.html
  app/views/products/createrecurringdepositproduct.html
  app/views/products/createsavingproduct.html
  app/views/products/createshareproduct.html
Labels: size/S

#2861 Fix #2842 - Added pagination
  app/scripts/controllers/accounting/AccCoaController.js
  app/scripts/controllers/configurations/GlobalConfigurationController.js
  app/scripts/controllers/organization/EmployeeController.js
  app/scripts/controllers/organization/HolController.js
  app/scripts/controllers/organization/OfficesController.js
  app/scripts/controllers/organization/RoleController.js
  app/scripts/controllers/organization/cashmgmt/TellersController.js
  app/scripts/controllers/organization/provisioning/ViewAllProvisoningCriteriaController.js
  app/scripts/controllers/product/ChargeController.js
  app/scripts/controllers/product/FixedDepositProductController.js
  app/scripts/controllers/product/LoanProductController.js
  app/scripts/controllers/product/RecurringDepositProductController.js
  app/scripts/controllers/product/SavingProductController.js
  app/scripts/controllers/product/ShareProductController.js
  app/scripts/controllers/reports/ViewReportsController.js
  app/scripts/controllers/system/CodeController.js
  app/scripts/controllers/system/DataTableController.js
  app/scripts/controllers/system/HookController.js
  app/scripts/controllers/system/ManageSurveysController.js
  app/scripts/controllers/system/ReportsController.js
  app/scripts/controllers/user/UserListController.js
  app/views/accounting/accounting_coa.html
  app/views/administration/global.html
  app/views/administration/roles.html
  app/views/administration/userslist.html
  app/views/organization/cashmgmt/tellers.html
  app/views/organization/employees.html
  app/views/organization/holidays.html
  app/views/organization/offices.html
  app/views/organization/provisioning/ViewAllProvisioningCriteria.html
  app/views/products/charges.html
  app/views/products/fixeddepositproducts.html
  app/views/products/loanproducts.html
  app/views/products/recurringdepositproducts.html
  app/views/products/savingproducts.html
  app/views/products/shareproducts.html
  app/views/reports/view_reports.html
  app/views/surveys/surveys.html
  app/views/system/codes.html
  app/views/system/datatables.html
  app/views/system/hooks.html
  app/views/system/reports.html
Labels: size/M

#2864 Fix #2863 Update UI of Tax Configurations
  app/views/products/tax/TaxConfigurations.html
Labels: size/XS

#2867 Fix #2373 UI for Creating Template Updated
  app/scripts/controllers/template/CreateTemplateController.js
  app/scripts/controllers/template/EditTemplateController.js
  app/styles-dev/main/components/_report.scss
  app/styles/styles.css
  app/views/templates/createtemplate.html
  app/views/templates/edittemplate.html
Labels: size/L

#2868 Fix #2865 - Hide the next and previous and added cancel
  app/scripts/controllers/shares/CreateShareAccountController.js
  app/views/loans/newloanaccount.html
  app/views/savings/new_saving_account_application.html
  app/views/shares/createshareaccount.html
Labels: size/XS
