Repository openMF/community-app, pull requests merged in 2018-02, with the labels that each got.

#2711 Fix #2707 - UI bug in "cashiersForTeller" page
  app/views/organization/cashmgmt/cashiersForTeller.html
Labels: size/XS

#2720 Fix #2558 - Fixed adding of groups in Manage Groups in Center
  app/scripts/controllers/centers/ManageGroupMembersController.js
  app/views/centers/managegroupmembers.html
Labels: size/XS

#2724 Fix #2723 - Corrected the column names in view closed loans
  app/views/clients/viewclient.html
Labels: size/XS

#2726 fix #2386-moratorium values not displaying properly
  app/views/loans/newloanaccount.html
Labels: size/XS

#2727 Fix #2693 Scrollbar hiding under the nav bar
  app/styles-dev/main/components/_layout.scss
  app/styles/styles.css
Labels: size/M

#2735 Fix #2097 - Make design for new applications the same
  app/views/deposits/fixed/newapplication.html
  app/views/deposits/recurring/newapplication.html
  app/views/loans/newloanaccount.html
  app/views/savings/new_saving_account_application.html
  app/views/shares/createshareaccount.html
Labels: size/XXL

#2738 fix #2733-create buttons properly padded
  app/views/products/charges.html
  app/views/products/fixeddepositproducts.html
  app/views/products/productmix/productmix.html
  app/views/products/recurringdepositproducts.html
  app/views/products/savingproducts.html
  app/views/products/shareproducts.html
Labels: size/XS

#2744 Fix #2743 - Enabled the selection of Date Of Birth before 1/01/2018
  app/views/clients/createclient.html
Labels: size/XS

#2761 Fix #2760 - Fixed the popover to show description in Create loan Products
  app/views/products/createloanproduct.html
Labels: size/XS

#2770 Fix #2763 - Added form validation to certain fields in "Create Fixed Deposit Product"
  app/views/products/createfixeddepositproduct.html
Labels: size/XS

#2715 Fix for #2439 - Can not Undo Approval Share Account after adding Note
  app/scripts/controllers/shares/ShareAccountActionsController.js
Labels: size/XS

#2719 Fixed for #2718 - SMS Campaign typos
  app/global-translations/locale-en.json
  app/views/organization/smscampaigns/editsmscampaign.html
  app/views/organization/smscampaigns/smscampaigns.html
  app/views/organization/smscampaigns/viewsmscampaign.html
Labels: size/XS

#2747 Fix #2745 - Properly aligned the fields in charges
  app/views/loans/newloanaccount.html
Labels: size/XS

#2741 fix #2740 - Date of Birth of client cannot be edited to the previous date in client
  app/views/clients/editclient.html
Labels: size/XS

#2750 Fix #2749 : adds validation for existing funds
  app/scripts/controllers/organization/ManageFundsController.js
  app/views/organization/managefunds.html
Labels: size/XS

#2751 fix #2742-scroll to top not working
  app/views/products/viewloanproduct.html
  app/views/products/viewrecurringdepositproduct.html
  app/views/products/viewsavingproduct.html
  app/views/products/viewshareproduct.html
Labels: size/XS

#2706 Fix #1723 - Show missing fields in Edit Saving Application
  app/scripts/controllers/savings/EditSavingAccountController.js
  app/views/savings/edit_saving_account_application.html
Labels: size/XS

#2762 Fix #2757 Popover keeps on flashing in Create User
  app/views/administration/createuser.html
Labels: size/XS

#2772 Fix #2766 Validation and Popover issue in Floating Rate Section
  app/views/products/floatingrates/CreateFloatingRate.html
  app/views/products/floatingrates/EditFloatingRate.html
  app/views/products/floatingrates/ViewFloatingRate.html
Labels: size/XS

#2773 Fix #2769 Breadcrumb links to non existing page in Add Charge(Client)
  app/scripts/controllers/client/AddNewClientChargeController.js
  app/views/clients/addnewclientcharge.html
Labels: size/XS

#2778 Fix #2764 - Fixed next and previous buttons in create group form
  app/views/groups/creategroup.html
Labels: size/XS

#2788 Fix #2781 - Show items in drop-down in top navbar on hover
  app/views/_topnavbar.html
Labels: size/XS

#2790 Fix #2789 Validation message overlap with dropdown in Create entity data table checks
  app/views/organization/entitydatatablechecks/entitydatatablechecks.html
Labels: size/XS

#2804 Fix #2795 Allowing user to skip over steps by clicking directly on progress bar with proper indication of validation
  app/scripts/modules/angular-wizard.js
Labels: size/XS

#2504 bulk-import-ui-for-all-modules
  app/global-translations/locale-en.json
  app/scripts/controllers/accounting/BulkImportCOAController.js
  app/scripts/controllers/accounting/BulkImportJournalEntriesController.js
  app/scripts/controllers/centers/BulkImportCentersController.js
  app/scripts/controllers/client/BulkImportClientsController.js
  app/scripts/controllers/deposits/fixed/BulkImportFixedDepositAccountsController.js
  app/scripts/controllers/deposits/fixed/BulkImportFixedDepositTransactionsController.js
  app/scripts/controllers/deposits/recurring/BulkImportRecurringDepositController.js
  app/scripts/controllers/deposits/recurring/BulkImportRecurringDepositTransactionsController.js
  app/scripts/controllers/groups/BulkImportGroupController.js
  app/scripts/controllers/loanAccount/BulkImportGuarantorController.js
  app/scripts/controllers/loanAccount/BulkImportLoanAccountsController.js
  app/scripts/controllers/loanAccount/BulkImportLoanRepaymentController.js
  app/scripts/controllers/organization/BulkImportEmployeeController.js
  app/scripts/controllers/organization/BulkImportOfficesController.js
  app/scripts/controllers/savings/BulkImportSavingsAccountController.js
  app/scripts/controllers/savings/BulkImportSavingsAccountsTransactionsController.js
  app/scripts/controllers/shares/BulkImportShareAccountController.js
  app/scripts/controllers/user/BulkImportUsersController.js
  app/scripts/mifosXComponents.js
  app/scripts/routes.js
  app/scripts/services/ResourceFactoryProvider.js
  app/views/administration/organization.html
  app/views/centers/centers.html
  app/views/clients/clients.html
  app/views/organization/bulkimport/bulkimport.html
  app/views/organization/bulkimport/bulkimportcenters.html
  app/views/organization/bulkimport/bulkimportclients.html
  app/views/organization/bulkimport/bulkimportcoa.html
  app/views/organization/bulkimport/bulkimportemployees.html
  app/views/organization/bulkimport/bulkimportfixeddepositaccounts.html
  app/views/organization/bulkimport/bulkimportfixeddeposittransactions.html
  app/views/organization/bulkimport/bulkimportgroup.html
  app/views/organization/bulkimport/bulkimportguarantor.html
  app/views/organization/bulkimport/bulkimportjournalentries.html
  app/views/organization/bulkimport/bulkimportloanaccounts.html
  app/views/organization/bulkimport/bulkimportloanrepayments.html
  app/views/organization/bulkimport/bulkimportoffices.html
  app/views/organization/bulkimport/bulkimportrecurringdeposits.html
  app/views/organization/bulkimport/bulkimportrecurringdepositstransactions.html
  app/views/organization/bulkimport/bulkimportsavingsaccounts.html
  app/views/organization/bulkimport/bulkimportsavingsaccountstransactions.html
  app/views/organization/bulkimport/bulkimportshareaccounts.html
  app/views/organization/bulkimport/bulkimportusers.html
  app/views/organization/employees.html
  app/views/organization/offices.html
Labels: size/XXL

#2810 Fix #1872 - Closed Center, Group& Clients are shown on User Interface
  app/global-translations/locale-en.json
  app/scripts/controllers/centers/CenterController.js
  app/scripts/controllers/client/ClientController.js
  app/scripts/controllers/groups/GroupController.js
  app/views/centers/centers.html
  app/views/clients/clients.html
  app/views/groups/groups.html
Labels: size/XS
