Repository openMF/community-app, pull requests merged in 2021-03, with the labels that each got.

#2873 fix #2777 : scroll to top feature implemented
  app/scripts/controllers/accounting/AccCoaController.js
  app/scripts/controllers/accounting/AccountingClosureController.js
  app/scripts/controllers/accounting/AccountingRuleController.js
  app/scripts/controllers/reports/ViewReportsController.js
  app/views/accounting/accounting_coa.html
  app/views/accounting/accounting_rules.html
  app/views/accounting/accounts_closure.html
  app/views/reports/view_reports.html
Labels: size/S

#2725 Fix #2181 - Not Allowing to Approve in 'view checker inbox' to create a new datatable
  app/scripts/services/ResourceFactoryProvider.js
Labels: size/XS

#2686 Fix #2683 - Tooltip for red loan account should be "Active in Bad Standing"
  app/scripts/controllers/client/ViewClientController.js
Labels: backend-left, size/XS

#2902 Fix #2899 Inconsistency in the UI of the app
  app/views/accounting/createglaccounting.html
  app/views/accounting/editglaccounting.html
  app/views/accounting/viewglaccounting.html
  app/views/adhocquery/adhocquerylists.html
  app/views/adhocquery/createadhocquery.html
Labels: size/M
